project_id: "mug-delhi"
location: "us-central1"
gemini_model_name: "gemini-1.5-flash-002"
embedding_model_name: "text-embedding-004"
image_generation_model_name: "imagen-3.0-fast-generate-002"
database: "(default)"
collection: "poses"
test_collection: "test-poses"
top_k: "3"
embedding_size: "768"
db_name: "gcp-yogaposes-db"
collection_name: "gcp-yogaposes-vectorstore"
atlas_vector_search_index_name: "gcp-yogaposes-search-index"
mongodb_atlas_cluster_uri: ""